[ADD] Player entity
onggarorynbassar/collector pull request #1
Opened 2021-09-23 12:45 UTC by adikmain

[Change] application.properties password for postgres

2021-09-23 14:05 UTC, Orynbasar requested changes

2021-09-23 14:05 UTC, Orynbasar commented on src/main/resources/application.properties
> +spring.datasource.password=${DB_PASSWORD:Adiqq228}
держи это у себя локально. Не надо комитить такое

2021-09-23 14:05 UTC, Orynbasar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +    )
Убери это, @GeneratedValue(strategy = GenerationType.AUTO) 
достаточно. У нас на стороне БД будут генериться ID

2021-09-23 16:05 UTC, Orynbasar requested changes

2021-09-23 16:05 UTC, Orynbasar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +    private int simple_mmr;
camel case: simpleMmr

2021-09-24 07:33 UTC, onggarorynbassar requested changes

2021-09-24 07:33 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +@Entity
Где @Table аннотация ?

2021-09-24 07:33 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +    private String steam_id;
steamId

2021-09-24 07:33 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +    private int relativeMmr;
зачем  указывать  @Column(name = "relative_mmr", nullable = false)? 
Hibernate сам сможет понять что relative_mmr это relativeMmr например. + nullable = false для INT ничего не значит

2021-09-24 07:46 UTC, onggarorynbassar requested changes

2021-09-24 07:46 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +@Table(name = "player")
укажи схему

2021-09-24 07:46 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +    @Column
@Column аннотация вообще не нужна

2021-09-24 07:52 UTC, onggarorynbassar requested changes

2021-09-24 07:52 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +@Table(name = "player", schema = "collector")
schema и потом table name

2021-09-24 07:52 UTC, onggarorynbassar commented on src/main/java/kz/onggar/collector/entity/Player.java
> +    private String steamId;
зря ты убрал @Column nullable false с этой переменной

2021-09-24 08:00 UTC, merged